// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:1
func StreamBase(qw422016 *qt422016.Writer, title string, page string) {
//line templates/base.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <title>`)
//line templates/base.qtpl:5
	qw422016.E().S(title)
//line templates/base.qtpl:5
	qw422016.N().S(` | Insta-Wiki</title>
    <link rel="stylesheet" href="/static/style.css">

    <link rel="stylesheet" href="/static/simplemde.min.css">
    <script src="/static/simplemde.min.js"></script>

    <link rel="stylesheet" href="/static/highlight.min.css">
    <script src="/static/highlight.min.js"></script>
</head>
<body>
<header>
    <div class="wrap">
        <a href="/"><h1>Insta-Wiki</h1></a>
        <form action="/search">
            <input type="text" name="query" id="query" placeholder="Search">
        </form>
        <nav>
            <a href="/wiki/new">New Page</a>
        </nav>
    </div>
</header>

<div class="content wrap">`)
//line templates/base.qtpl:27
	qw422016.N().S(page)
//line templates/base.qtpl:27
	qw422016.N().S(`</div>
</body>
</html>
`)
//line templates/base.qtpl:30
}

//line templates/base.qtpl:30
func WriteBase(qq422016 qtio422016.Writer, title string, page string) {
//line templates/base.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:30
	StreamBase(qw422016, title, page)
//line templates/base.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:30
}

//line templates/base.qtpl:30
func Base(title string, page string) string {
//line templates/base.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:30
	WriteBase(qb422016, title, page)
//line templates/base.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:30
	return qs422016
//line templates/base.qtpl:30
}
