// Code generated by qtc from "edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/edit.qtpl:1
package templates

//line templates/edit.qtpl:1
import "github.com/ucosty/insta-wiki/models"

//line templates/edit.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/edit.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/edit.qtpl:3
func StreamEditContent(qw422016 *qt422016.Writer, page *models.Page) {
//line templates/edit.qtpl:3
	qw422016.N().S(`
<div class="editor wrap">
    `)
//line templates/edit.qtpl:5
	if !page.IsNewPage {
//line templates/edit.qtpl:5
		qw422016.N().S(`
    <nav class="tabs">
        <a href="/wiki/`)
//line templates/edit.qtpl:7
		qw422016.E().S(page.Path)
//line templates/edit.qtpl:7
		qw422016.N().S(`/history">History</a>
        <a href="/wiki/`)
//line templates/edit.qtpl:8
		qw422016.E().S(page.Path)
//line templates/edit.qtpl:8
		qw422016.N().S(`/edit" class="selected">Edit</a>
        <a href="/wiki/`)
//line templates/edit.qtpl:9
		qw422016.E().S(page.Path)
//line templates/edit.qtpl:9
		qw422016.N().S(`">Read</a>
    </nav>
    `)
//line templates/edit.qtpl:11
	}
//line templates/edit.qtpl:11
	qw422016.N().S(`

    <form action="/wiki/`)
//line templates/edit.qtpl:13
	qw422016.E().S(page.Path)
//line templates/edit.qtpl:13
	qw422016.N().S(`" method="post">
        <div class="metadata">
            <label for="title">Page Title</label>
            <input type="text" name="title" id="title" placeholder="Page Title" value="`)
//line templates/edit.qtpl:16
	qw422016.E().S(page.Title)
//line templates/edit.qtpl:16
	qw422016.N().S(`">

            <label for="path">Page Path</label>
            <input type="text" name="path" id="path" placeholder="Page Path" value="`)
//line templates/edit.qtpl:19
	qw422016.E().S(page.Path)
//line templates/edit.qtpl:19
	qw422016.N().S(`">
        </div>

        <textarea name="body" id="markdown-editor" cols="30" rows="10">`)
//line templates/edit.qtpl:22
	qw422016.E().S(page.BodyMarkdown)
//line templates/edit.qtpl:22
	qw422016.N().S(`</textarea>
        <input type="submit" value="Save">
    </form>
</div>

<script>
var editor = new SimpleMDE({ element: document.getElementById("markdown-editor") });
</script>
`)
//line templates/edit.qtpl:30
}

//line templates/edit.qtpl:30
func WriteEditContent(qq422016 qtio422016.Writer, page *models.Page) {
//line templates/edit.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/edit.qtpl:30
	StreamEditContent(qw422016, page)
//line templates/edit.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/edit.qtpl:30
}

//line templates/edit.qtpl:30
func EditContent(page *models.Page) string {
//line templates/edit.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/edit.qtpl:30
	WriteEditContent(qb422016, page)
//line templates/edit.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/edit.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/edit.qtpl:30
	return qs422016
//line templates/edit.qtpl:30
}

//line templates/edit.qtpl:32
func StreamEdit(qw422016 *qt422016.Writer, page *models.Page) {
//line templates/edit.qtpl:32
	qw422016.N().S(`
`)
//line templates/edit.qtpl:33
	StreamBase(qw422016, page.Title, EditContent(page))
//line templates/edit.qtpl:33
	qw422016.N().S(`
`)
//line templates/edit.qtpl:34
}

//line templates/edit.qtpl:34
func WriteEdit(qq422016 qtio422016.Writer, page *models.Page) {
//line templates/edit.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/edit.qtpl:34
	StreamEdit(qw422016, page)
//line templates/edit.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line templates/edit.qtpl:34
}

//line templates/edit.qtpl:34
func Edit(page *models.Page) string {
//line templates/edit.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/edit.qtpl:34
	WriteEdit(qb422016, page)
//line templates/edit.qtpl:34
	qs422016 := string(qb422016.B)
//line templates/edit.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/edit.qtpl:34
	return qs422016
//line templates/edit.qtpl:34
}
