// Code generated by qtc from "history.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/history.qtpl:1
package templates

//line templates/history.qtpl:1
import "github.com/ucosty/insta-wiki/models"

//line templates/history.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/history.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/history.qtpl:3
func StreamHistoryContent(qw422016 *qt422016.Writer, page *models.Page, results []models.Page) {
//line templates/history.qtpl:3
	qw422016.N().S(`
<div class="content wrap">
    <nav class="tabs">
        <a href="/wiki/`)
//line templates/history.qtpl:6
	qw422016.E().S(page.Path)
//line templates/history.qtpl:6
	qw422016.N().S(`/history" class="selected">History</a>
        <a href="/wiki/`)
//line templates/history.qtpl:7
	qw422016.E().S(page.Path)
//line templates/history.qtpl:7
	qw422016.N().S(`/edit">Edit</a>
        <a href="/wiki/`)
//line templates/history.qtpl:8
	qw422016.E().S(page.Path)
//line templates/history.qtpl:8
	qw422016.N().S(`">Read</a>
    </nav>
    <ol>
        `)
//line templates/history.qtpl:11
	for _, result := range results {
//line templates/history.qtpl:11
		qw422016.N().S(`
        <li>
            <a href="/wiki/`)
//line templates/history.qtpl:13
		qw422016.E().S(result.Path)
//line templates/history.qtpl:13
		qw422016.N().S(`">`)
//line templates/history.qtpl:13
		qw422016.E().S(result.Title)
//line templates/history.qtpl:13
		qw422016.N().S(`</a>
        </li>
        `)
//line templates/history.qtpl:15
	}
//line templates/history.qtpl:15
	qw422016.N().S(`
    </ol>
</div>
`)
//line templates/history.qtpl:18
}

//line templates/history.qtpl:18
func WriteHistoryContent(qq422016 qtio422016.Writer, page *models.Page, results []models.Page) {
//line templates/history.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/history.qtpl:18
	StreamHistoryContent(qw422016, page, results)
//line templates/history.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/history.qtpl:18
}

//line templates/history.qtpl:18
func HistoryContent(page *models.Page, results []models.Page) string {
//line templates/history.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/history.qtpl:18
	WriteHistoryContent(qb422016, page, results)
//line templates/history.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/history.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/history.qtpl:18
	return qs422016
//line templates/history.qtpl:18
}

//line templates/history.qtpl:20
func StreamHistory(qw422016 *qt422016.Writer, page *models.Page, results []models.Page) {
//line templates/history.qtpl:20
	qw422016.N().S(`
`)
//line templates/history.qtpl:21
	StreamBase(qw422016, page.Title, HistoryContent(page, results))
//line templates/history.qtpl:21
	qw422016.N().S(`
`)
//line templates/history.qtpl:22
}

//line templates/history.qtpl:22
func WriteHistory(qq422016 qtio422016.Writer, page *models.Page, results []models.Page) {
//line templates/history.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/history.qtpl:22
	StreamHistory(qw422016, page, results)
//line templates/history.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/history.qtpl:22
}

//line templates/history.qtpl:22
func History(page *models.Page, results []models.Page) string {
//line templates/history.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/history.qtpl:22
	WriteHistory(qb422016, page, results)
//line templates/history.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/history.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/history.qtpl:22
	return qs422016
//line templates/history.qtpl:22
}
