// Code generated by qtc from "search.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/search.qtpl:1
package templates

//line templates/search.qtpl:1
import "github.com/ucosty/insta-wiki/models"

//line templates/search.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/search.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/search.qtpl:3
func StreamSearchContent(qw422016 *qt422016.Writer, query string, page int64, results []models.Page) {
//line templates/search.qtpl:3
	qw422016.N().S(`
<div class="content wrap">
<ol>
    `)
//line templates/search.qtpl:6
	for _, result := range results {
//line templates/search.qtpl:6
		qw422016.N().S(`
    <li>
        <a href="/wiki/`)
//line templates/search.qtpl:8
		qw422016.E().S(result.Path)
//line templates/search.qtpl:8
		qw422016.N().S(`">`)
//line templates/search.qtpl:8
		qw422016.E().S(result.Title)
//line templates/search.qtpl:8
		qw422016.N().S(`</a>
    </li>
    `)
//line templates/search.qtpl:10
	}
//line templates/search.qtpl:10
	qw422016.N().S(`
</ol>
</div>
`)
//line templates/search.qtpl:13
}

//line templates/search.qtpl:13
func WriteSearchContent(qq422016 qtio422016.Writer, query string, page int64, results []models.Page) {
//line templates/search.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/search.qtpl:13
	StreamSearchContent(qw422016, query, page, results)
//line templates/search.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line templates/search.qtpl:13
}

//line templates/search.qtpl:13
func SearchContent(query string, page int64, results []models.Page) string {
//line templates/search.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/search.qtpl:13
	WriteSearchContent(qb422016, query, page, results)
//line templates/search.qtpl:13
	qs422016 := string(qb422016.B)
//line templates/search.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/search.qtpl:13
	return qs422016
//line templates/search.qtpl:13
}

//line templates/search.qtpl:15
func StreamSearch(qw422016 *qt422016.Writer, query string, page int64, results []models.Page) {
//line templates/search.qtpl:15
	qw422016.N().S(`
`)
//line templates/search.qtpl:16
	StreamBase(qw422016, "Search", SearchContent(query, page, results))
//line templates/search.qtpl:16
	qw422016.N().S(`
`)
//line templates/search.qtpl:17
}

//line templates/search.qtpl:17
func WriteSearch(qq422016 qtio422016.Writer, query string, page int64, results []models.Page) {
//line templates/search.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/search.qtpl:17
	StreamSearch(qw422016, query, page, results)
//line templates/search.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line templates/search.qtpl:17
}

//line templates/search.qtpl:17
func Search(query string, page int64, results []models.Page) string {
//line templates/search.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/search.qtpl:17
	WriteSearch(qb422016, query, page, results)
//line templates/search.qtpl:17
	qs422016 := string(qb422016.B)
//line templates/search.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/search.qtpl:17
	return qs422016
//line templates/search.qtpl:17
}
